import type { MemoryItem } from "./memories.types";

export const MEMORY_ITEMS: readonly MemoryItem[] = [
  {
    id: "family-blessings",
    caption: "Blessings from home",
    aspect: "tall",
    rotate: -2.5,
    gradient: { from: "gold", to: "peach", accent: "maroon" },
    likes: 128,
    illustration: "family-meeting",
  },
  {
    id: "celebration-feast",
    caption: "Feast of joy",
    aspect: "square",
    rotate: 1.8,
    gradient: { from: "green", to: "maroon", accent: "gold" },
    likes: 156,
    illustration: "family-gathering",
  },
  {
    id: "wedding-vows",
    caption: "Under the golden arch",
    aspect: "landscape",
    rotate: -1.2,
    gradient: { from: "maroon", to: "navy", accent: "gold" },
    likes: 203,
    illustration: "wedding-arch",
  },
  {
    id: "mandap-moments",
    caption: "Sacred mandap vows",
    aspect: "portrait",
    rotate: 2.4,
    gradient: { from: "peach", to: "gold", accent: "maroon" },
    likes: 241,
    illustration: "sacred-fire",
  },
  {
    id: "cake-cutting",
    caption: "Sweet beginnings",
    aspect: "square",
    rotate: -1.6,
    gradient: { from: "ivory", to: "green", accent: "gold" },
    likes: 187,
    illustration: "cake-cutting",
  },
  {
    id: "together-forever",
    caption: "Two hearts, one story",
    aspect: "tall",
    rotate: 1.4,
    gradient: { from: "maroon", to: "gold", accent: "ivory" },
    likes: 134,
    illustration: "family-meeting",
  },
  {
    id: "sangeet-night",
    caption: "Music & marigolds",
    aspect: "landscape",
    rotate: -2,
    gradient: { from: "peach", to: "maroon", accent: "gold" },
    likes: 112,
    illustration: "cake-cutting",
  },
  {
    id: "homecoming",
    caption: "Families united",
    aspect: "portrait",
    rotate: 1.1,
    gradient: { from: "navy", to: "maroon", accent: "peach" },
    likes: 178,
    illustration: "family-gathering",
  },
  {
    id: "golden-hour",
    caption: "Golden hour whispers",
    aspect: "square",
    rotate: -0.8,
    gradient: { from: "gold", to: "green", accent: "maroon" },
    likes: 94,
    illustration: "wedding-arch",
  },
  {
    id: "forever-begins",
    caption: "Forever begins here",
    aspect: "portrait",
    rotate: 2,
    gradient: { from: "maroon", to: "peach", accent: "gold" },
    likes: 265,
    illustration: "sacred-fire",
  },
] as const;

export const MASONRY_COLUMN_CLASS =
  "columns-2 gap-4 sm:columns-3 sm:gap-5 lg:columns-3 xl:columns-4";
